export const debugDefaults = {
  login: { email: 'admin@autozona.com', password: 'admin123' },
  register: {
    name: 'Juan Test',
    email: 'test@example.com',
    phone: '1155001234',
    password: 'test1234',
  },
  profile: {
    name: 'Juan Test',
    email: 'test@example.com',
    phone: '1155001234',
    password: '',
  },
  search: {
    brand: '',
    priceMax: '',
    location: '',
  },
  filters: {
    search: '',
    brand: '',
    fuel: '',
    transmission: '',
    yearFrom: '',
    yearTo: '',
    priceMin: '',
    priceMax: '',
    kmMax: '',
    sort: 'newest',
  },
  listing: {
    title: 'Toyota Corolla 2022 TEST',
    brand: 'Toyota',
    model: 'Corolla',
    year: '2022',
    mileage: '15000',
    fuel: 'Nafta',
    transmission: 'Automática',
    engine: '2.0L',
    priceArs: '18000000',
    priceUsd: '20000',
    location: 'Buenos Aires',
    phone: '1155001234',
    description: 'Vehículo en excelente estado, único dueño.',
    images: '/hilux.png',
    equipment: 'Airbag, ABS, Cámara de reversa, Control crucero',
    status: 'ACTIVE',
    featured: false,
    verified: true,
  },
  user: {
    name: 'Usuario Debug',
    email: 'debug@example.com',
    password: 'debug1234',
    phone: '1155001234',
    role: 'USER',
    approvalStatus: 'APPROVED',
    planId: '',
  },
  plan: {
    name: 'Plan Debug',
    price: '55000',
    maxImages: '8',
    daysActive: '30',
    features: '8 imágenes, Informe de dominio, Documentación verificada, Contacto por WhatsApp',
  },
};
